### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [willgpaik/qt5_aci#1]
Hey @willgpaik ! I've noticed that you build your main containers very frequently, the most frequently of any user since we came online. I want to suggest that you either do a manual (via the interface) or [deployment build](https://singularityhub.github.io/singularityhub-docs/docs/builds/deployment), because every time you build Singularity Hub is paying for a builder instance. It would be really great if you could optimize your development workflow for that. Thanks!

**Comment by willgpaik** [comment]
@vsoch I'm sorry for building too frequently. I'll try to test build offline before submitting to Singularity Hub. What do you mean by manual? This collection from Singularity Hub is only triggered manually. If you are talking about the other container I was building today, I'll make sure to set it back to manual build.

**Comment by vsoch** [comment]
hey @willgpaik ! If you need to build, it's totally okay - I mostly want to have conversation / teach about best practices building collections based on the frequency of updates, etc. You are *well* within a reasonable range and I'm just double checking that the builds are what you intend to do (many users will build on commit and then forget, and commit a lot of times, haha). Please close if you are already aware of these options, and happy building!

**Comment by willgpaik** [comment]
@vsoch I've been trying to build same container multiple times through Singularity Hub. I tested it on 2 different machines without any issue (using version 3.1.1) but builder from Singularity Hub (version 2.5.0) kept encountering error. So, it was generating broken containers.

Also, I recently tried to build with builder version 3.2.1 from Singularity Hub twice, but it failed to read correct recipe file. I wanted to build Singularity.qt5 but it was building Singularity. Could you please check it out for me? Thank you!

**Comment by vsoch** [comment]
Could you link me to the container with the build issue for 2.5?

**Comment by vsoch** [comment]
The logs for 3.2.1 would be helpful too. That's an unannounced testing builder.

**Comment by willgpaik** [comment]
@vsoch Link to the container is https://singularity-hub.org/collections/2152# and I was working on container with recipe Singularity.qt5. Log can be found: https://singularity-hub.org/containers/10078/log

Are containers forward compatible? Cluster I have access is using version 3.1.1. Since build with 2.5.0 failed, I might need to build with 3.2.1 once it's tested.

**Comment by vsoch** [comment]
Your cluster won't be forward compatible - so there's a chance 3.2.1 won't work with 3.1.1. But it should be backwards compatible, so 2.5.1 should work. Where is the log for the 2.5 build (that failed?)

**Comment by willgpaik** [comment]
Since I rebuilt with 3.2.1, log was overwritten. Do you want me to rebuild with 2.5 and send you the log? I tested with version 2.6.0 and 3.1.1 without issue.

**Comment by vsoch** [comment]
hey @willgpaik yes please rebuild with 2.5! I've found the bug with the 3.2.1 builder, so I'll just need to recreate it (I can let you know when this is done, it takes a little time).

**Comment by vsoch** [comment]
hey @willgpaik I've added a new builder, ` singularity-builder-3-2-1-100-gb-private` for you to test - but let's please wait for the current build to finish so I can take a look at the log (let me know when it's done). In the future, when you have a failure (instead of rebuilding to infinitude) could you please share the log with me first?

**Comment by willgpaik** [comment]
Hi @vsoch please check the log: https://singularity-hub.org/containers/10078/log. In some reason, build spec is still showing different recipe. Error I got is:
```strip:/usr/local/Qt-5.12.5/bin/fixqt4headers.pl: File format not recognized
gmake: [install_fixqt4headers] Error 1 (ignored)
strip:/usr/local/Qt-5.12.5/bin/syncqt.pl: File format not recognized
gmake: [install_syncqt] Error 1 (ignored)
```
which didn't happen when I was building offline.

**Comment by willgpaik** [comment]
@vsoch I'm sorry but please ignore it. I just downloaded and it looks fine. Some symlinks should be re-assigned but otherwise everything seems to be installed. I actually have few other issues with another container but I'll ask you later.

**Comment by vsoch** [comment]
The error I'm seeing in the log is related to https://forum.qt.io/topic/49747/make-install-file-format-not-recognized/8, which is something about how you compile.

Another useful tidbit, you'll have an easy time if you use a docker centos base than the yum boostrap. There are almost always errors with it.

Did you try the new 3.2.1 builder, where the recipe is fixed? The log you linked is 2.5.

**Comment by vsoch** [comment]
Nevermind I'll test with a smaller container, less expense that way!

**Comment by willgpaik** [comment]
Thank you for updating me. No, I didn't test it with 3.2.1 yet. I can test it later but need to update Singularity on my PC first. Another thing I just found is that updated environment doesn't seem like to follow when I'm building a container from the other one. So, even though I updated PATH and LD_LIBRARY_PATH from %environment section, they are not recognized. Is there any way to automate it? I'm completely fine with adding few lines though.

**Comment by vsoch** [comment]
Don't worry about testing - I disabled that branch and I'll need to test further on my own. It's the end of the day here and this kind of testing usually takes me about 3 hours, so I'm not going to do it today. I'll likely have time sometime this week - ping me if you want any update.

**Comment by vsoch** [comment]
Both of those environment variables need to be set in the container, you can't set them from outside of it. There were SINGULARITYENV_* variables added at some later version, but I don't remember which one. For this issue you need to reach out to the Singularity developers, it's not an issue with Singularity Hub.
